package com.mycompany.achievementsapp.utils

object Constants {

     const val COROUTINE_TIMER_DELAY=50L

     const val ACHIEVEMENT_FRAGMENT_ARG_KEY="ACHIEVEMENT_FRAGMENT_ARG_KEY"

     const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
     const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
     const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
}